"""add composite indexes for hot query paths

Replaces six single-column (user_id / conversation_id) indexes with composite
indexes that match how the app actually reads: one user's rows, ordered by
time. The dropped columns are the leading column of their replacement, so
filters on them alone are still indexed.

Revision ID: 0002_composite_indexes
Revises: 0001_baseline
Create Date: 2026-09-08 22:13:35.498223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_composite_indexes'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.create_index('ix_ai_conversations_user_updated', 'ai_conversations', ['user_id', 'updated_at'], unique=False)
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.create_index('ix_ai_messages_conversation_created', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_device_readings_user_id'), table_name='device_readings')
    op.create_index('ix_device_readings_user_received', 'device_readings', ['user_id', 'received_at'], unique=False)
    op.drop_index(op.f('ix_health_entries_user_id'), table_name='health_entries')
    op.create_index('ix_health_entries_user_recorded', 'health_entries', ['user_id', 'recorded_at'], unique=False)
    op.drop_index(op.f('ix_medication_logs_user_id'), table_name='medication_logs')
    op.create_index('ix_medication_logs_user_logged', 'medication_logs', ['user_id', 'logged_at'], unique=False)
    op.drop_index(op.f('ix_risk_evaluations_user_id'), table_name='risk_evaluations')
    op.create_index('ix_risk_evaluations_user_created', 'risk_evaluations', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_evaluations_user_created', table_name='risk_evaluations')
    op.create_index(op.f('ix_risk_evaluations_user_id'), 'risk_evaluations', ['user_id'], unique=False)
    op.drop_index('ix_medication_logs_user_logged', table_name='medication_logs')
    op.create_index(op.f('ix_medication_logs_user_id'), 'medication_logs', ['user_id'], unique=False)
    op.drop_index('ix_health_entries_user_recorded', table_name='health_entries')
    op.create_index(op.f('ix_health_entries_user_id'), 'health_entries', ['user_id'], unique=False)
    op.drop_index('ix_device_readings_user_received', table_name='device_readings')
    op.create_index(op.f('ix_device_readings_user_id'), 'device_readings', ['user_id'], unique=False)
    op.drop_index('ix_ai_messages_conversation_created', table_name='ai_messages')
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.drop_index('ix_ai_conversations_user_updated', table_name='ai_conversations')
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###
