"""health_entries range CHECK constraints (spo2, heart rate)

Hand-written: Alembic autogenerate does not diff CHECK constraints, so the
autogenerated body was empty and these ops were added by hand.

Revision ID: 0003_health_entry_checks
Revises: 0002_composite_indexes
Create Date: 2026-09-08 22:24:29.436864

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_health_entry_checks"
down_revision: Union[str, Sequence[str], None] = "0002_composite_indexes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_check_constraint(
        "ck_health_entries_spo2_percent_range",
        "health_entries",
        "spo2_percent IS NULL OR (spo2_percent >= 0 AND spo2_percent <= 100)",
    )
    op.create_check_constraint(
        "ck_health_entries_heart_rate_bpm_range",
        "health_entries",
        "heart_rate_bpm IS NULL OR (heart_rate_bpm >= 0 AND heart_rate_bpm <= 300)",
    )


def downgrade() -> None:
    op.drop_constraint(
        "ck_health_entries_heart_rate_bpm_range", "health_entries", type_="check"
    )
    op.drop_constraint(
        "ck_health_entries_spo2_percent_range", "health_entries", type_="check"
    )
